#! /bin/sh

sxhkd &
picom &
wal -R
source "$HOME/.cache/wal/colors.sh"

$HOME/.config/polybar/scripts/launch.sh mainbar-bspwm

bspc monitor -d 1 2 3 4 5 

bspc config border_width         4
bspc config window_gap          12

bspc config focused_border_color $color1
bspc config presel_feedback_color $color1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
